---
# tasks/shell.yml

- name: Test | Shell | Result code
  shell: ls -1dt {{ ocstore_www_root }}/{{ ocstore_releases_dir }}/* | tail -n +{{ ocstore_keep_releases | int + 1 }}
  register: ocstore_delete_releases
  changed_when: false
  when: ocstore_keep_releases > 0

- debug:
    msg: "{{ ocstore_delete_releases.stdout_lines | length }}"

- name: Test | Shell | Init array of shell commands
  set_fact:
    cmds:
      - { name: "aaa", cmd: "echo" }
      - { name: "bbb", cmd: "echo" }
      - { cmd: "echo" }

- name: Test | Shell | Build one big command
  set_fact:
    cmd: |  
          {% for item in cmds %}
          {% if item.name is defined %}
          {{ item.cmd }} "{{ item.name }}";
          {% else %}
          {{ item.cmd }} "name not defined";
          {% endif %}
          {% endfor %}

- debug:
    msg: "{{ cmd }}"

- name: Test | Shell | Execute one big command
  shell: "{{ cmd }}"
  register: cmd_result
          
- debug:
    var: cmd_result
